### PR TITLE
Add Sensor Support

### PR DESCRIPTION
**Pull request by R0NAM1**
As said in AsteroidOS/meta-smartwatch#39:
During a single night, sensors got support, currently Skipjack has three sensors under SensorFWD:

    A Heartbeat Sensor
    A Tilt-To-Wake Sensor
    A Pedometer (Step Counter)

Currently the first two are working with their respective apps, it is assumed the third sensor works, but no real app has been built to use it, so for now it does not count towards anything. The process to get them work was the same as Ray And Firefish.

Build has been tested and does work fine with up to date system tar.

### CODE REVIEW

**Comment by R0NAM1** [comment]
Will update System Dir Recipe after no issues are found, through the usual way.

**Comment by R0NAM1** [comment]
Going to amend commit later with link to changes for the new System Dir.

**Comment by R0NAM1** [comment]
Amended.

**Comment by MagneFire** [comment]
Great work on getting sensors to work!

I'll merge this as is now. Looking good👍

One more idea to improve the git commit messages in the future would be to add the reason for the change/addition in any given commit.
Simply stating the things changed is usually also visible in the git diff.
For instance: the disabling of CONFIG_IPC_ROUTER_SECURITY is needed for the android service sensors.qcom to be able to communicate with the modem, having this enabled rejects communication.
I trap myself on not documenting these things properly too sometimes, but it's good practice to document it in the git commits 😊


You mentioned having seen support for three sensors: tilt-to-wake, pedometer and heart rate sensor. Does this watch not have an ambient light sensor?

**Pull request merged**
